spring.application.name=ferreteria-api

# espera variables de la nube aws
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}

# VARIABLES DIRECTAS DE SPRING BOOT
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.rvswrafkyahqblkdwarx
spring.datasource.password=viFopROrjd7RfsS8

# CONFIGURACION DE HIBERNATE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Seguridad Swagger: Encendido por defecto, pero apagable por variables de entorno
springdoc.api-docs.enabled=${ENABLE_SWAGGER:true}
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:true}